### ISSUE TITLE
False positives [nonportable_path_linter]

### ISSUE THREAD

**Issue by tonyk7440** [r-lib/lintr#2041] opened 2023-08-04 12:02 UTC
It seems to me that lintr is incorrectly interpreting some date formatting as a file path
```
my_df %>%
  mutate(last_run_time = format(last_run_time, , "%A, %d/%b"))
```

Also another case is when referencing a user name in windows
```
tasks %>%
    filter(`Run As User` == "CORP\\sys_username")
```

Which both result in:
`[nonportable_path_linter] use file.path() to construct portable file paths`

**Comment by MichaelChirico** [comment] 2023-08-04 14:45
this should be a duplicate of #468, please re-open otherwise

**Closed by MichaelChirico** 2023-08-04 14:45 UTC
