### ISSUE TITLE
Release lintr 3.0.0

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#824] opened 2021-07-02 17:09 UTC
Prepare for release:

* [x] Merge all outstanding PRs for [3.0.0](https://github.com/jimhester/lintr/milestone/2)
* [x] #825
* [x] #827
* [x] #833
* [x] #828
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] #832 
* [x] #836
* [x] Update `cran-comments.md`
* [x] Draft blog post

Submit to CRAN:

* [x] `usethis::use_version('major')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version()`
* [x] Finish blog post
* [x] [Tweet](https://twitter.com/michael_chirico/status/1548028640545234944)
* [x] Add link to blog post in pkgdown news menu

**Comment by MichaelChirico** [comment] 2021-07-02 17:40
Aside: I can tell I've been working on translations too much lately that I read "Polish NEWS" as "🇵🇱 NEWS"

**Comment by AshesITR** [comment] 2021-07-02 17:44
Feel free to add or remove TODOs, I just used `usethis::use_release_issue()` to not forget anything.

**Comment by AshesITR** [comment] 2021-07-03 07:14
I've started a full `revdepcheck`, will upload the results later.

**Comment by russHyde** [comment] 2021-07-07 07:52
Could you add @AshesITR , @MichaelChirico  and @renkun-ken  as authors in DESCRIPTION prior to release. You've done really great work on lintr over the past year.

**Comment by lorenzwalthert** [comment] 2021-11-09 17:18
Any ETA on this?

**Comment by eitsupi** [comment] 2022-03-19 16:06
Thank you for your continued development. I am wondering when a new release is planned.
(It seems that most of what's on the to-do list has been accomplished.)

**Comment by MichaelChirico** [comment] 2022-03-21 00:16
I think #962 is the main blocker before going back into release cycle (checking revdeps, tidying NEWS, etc). @AshesITR any other thoughts?

**Comment by MichaelChirico** [comment] 2022-04-14 06:11
OK, just took another pass at triaging issues for this release. I am pretty happy with what'll be included based on the current milestone. @AshesITR feel free to update. 23 issues left, >1/2 of which have corresponding PRs, a few more are meta-issues related to the release itself. I think we're pretty close.

**Comment by MichaelChirico** [comment] 2022-05-19 20:34
Looking at the milestone, I think we're pretty much at "code freeze" stage -- shall I put out an announcement requesting early testing? Maybe after #1140?

**Comment by AshesITR** [comment] 2022-05-19 20:35
SGTM

**Comment by MichaelChirico** [comment] 2022-05-22 01:16
Noting here that Hadley offered to host a release blog post on the tidyverse blog:

https://twitter.com/hadleywickham/status/1528081727259824128

**Comment by MichaelChirico** [comment] 2022-06-02 00:47
Finally got latest dev working internally and did a full run of 2.0.1 vs. roughly aec989e223371396255554d9c675c703438dcbdb (I'll just call it 3.0) and am comparing. Note that ~most lints at our HEAD were already cleaned, so the baseline is relatively low. here's a rough summary of the observed changes:

 - ~1% of lints found in 2.0.1 are gone in 3.0
   - ✅ about half are from ignoring trailing whitespace in strings in `trailing_whitespace_linter`
   - ✅ about 13% are from `paren_brace_linter` false positives matching inside strings (mainly regexes/CSS)
   - ✅ about 10% are from `T_and_F_symbol_linter` false positives like `foo$T`
   - ✅ about 10% are from `commas_linter` false positives like `switch(x, a = , b = 2)`
   - ❌ about 13% are from false negatives in `infix_spaces_linter`: #1342
   - ❌ about 10% are from mismatch in metadata for `spaces_inside_linter`: #1343
 - ~25% of lints found in 3.0 were not there in 2.0.1
   - ✅ about 10% are on the new `missing_argument_linter`; a decent number would fit under #1152
   - ✅ about 10% are thanks to improvements in `fixed_regex_linter`, e.g. when named arguments are given
   - ✅ about 3% are thanks to improvements in `infix_spaces_linter`, e.g. `function(x=1)`, `y~x`, etc.
   - ✅ about 1% are additions to `paste_linter` for `paste0(sep = .)`
   - ✅ about 1% are new hits on completely blank lines for `trailing_whitespace_linter`
   - ✅ about 1% are thanks to improvements in `conjunct_test_linter` to include `assert_that`
   - ✅ about 1% are thanks to improvements in `trailing_blank_lines_linter` to catch missing terminal newlines
   - ✅ about 1% are thanks to improvements in `function_left_parentheses_linter` to catch usages across >1 line like `foo\n()`
   - ✅ about 1% are thanks to selectively disabling linters revealing code that was in `#nolint` regions but violated unrelated rules
   - ✅ residual good things: new hits in `package_hooks_linter`, `expect_null_linter`, `inner_combine_linter`, `paren_body_linter`, ...
   - 🧐 about 15% are new hits on `brace_linter`, e.g. `function(x) {x[1]}`, but some seem OK: #1346
   - 🧐 about 15% are on the new `duplicate_argument_linter`; a lot seem due to `dplyr::mutate()`: #1345
   - ❌ about 33% are from improvements to `unneeded_concatenation_linter` that probably go to far: #1344

**Comment by MichaelChirico** [comment] 2022-06-02 00:49
oh, also, the full run took about 20% less time overall. I was working more during the slower run, but not enough to make that big a difference. there's a lot of other overhead to our system that means this figure probably doesn't generalize well, but if anything, I'd guess the typical user will see >20% improvement.

**Comment by jimhester** [comment] 2022-06-12 14:28
latest CRAN communication

> package lintr is now scheduled for archival on 2022-06-26, and
archiving this will necessitate also archiving its CRAN strong reverse
dependencies.

from looking at the above this shouldn’t be hard to meet, but we should get this release out sooner rather than later.

**Comment by AshesITR** [comment] 2022-06-12 21:48
@jimhester I think we're ready for the final steps. Since you are the maintainer, you'll receive the mails from `devtools::check_win_devel()` et al. Do you want to start them yourself?

I'm running a final revdepcheck to get #832 done ad would leave the rest to you if that's fine?

**Comment by jimhester** [comment] 2022-06-13 14:20
Ok, I have finished up the last few things and submitted the package, will update this once it is accepted.

**Comment by MichaelChirico** [comment] 2022-06-14 05:09
I see us on CRAN! thanks Jim!!

**Comment by bersbersbers** [comment] 2022-06-14 05:12
Congratulations!

**Comment by MichaelChirico** [comment] 2022-06-14 23:13
Hmm looks like we are warning on oldrel:

https://www.r-project.org/nosvn/R.check/r-oldrel-macos-arm64/lintr-00check.html

```
checking examples ... [1s/1s] WARNING
Found the following significant warnings:

  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
  Warning: 'all.equal.default(<function>)' is deprecated.
Deprecated functions may be defunct as soon as of the next release of
R.
See ?Deprecated.
```

**Comment by jimhester** [comment] 2022-06-15 14:56
Seems like the oldrel-mac is lagging, it is only 4.1.1-patched, but 4.1.3 is released and is what we are testing against on the CI.

https://github.com/wch/r-source/commit/3506de09ab90a76d048def9a8a10badf1cc04259 is the relevant commit, which presumably was backported to later patch releases.

I don't think we need to do anything about that warning.

**Comment by MichaelChirico** [comment] 2022-06-15 15:11
4.1.2 is warning as well:

https://www.r-project.org/nosvn/R.check/r-oldrel-macos-x86_64/lintr-00check.html

**Comment by MichaelChirico** [comment] 2022-06-15 15:13
👍 sounds like we're unlikely to get archived then. 

I'm still wondering if we shouldn't revisit the S3 class of Linter() output

**Comment by MichaelChirico** [comment] 2022-06-20 02:06
looks like we're erroring on 3.0.0 -- I can't make heads or tails of what's wrong though:

https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/lintr-00check.html

**Comment by AshesITR** [comment] 2022-06-20 05:09
Looks to me as if the fixes we do might no longer be necessary in 4.3.0.
I'll try to update my r-devel and take a look.

**Comment by AshesITR** [comment] 2022-06-20 09:01
I fail to reproduce on R-devel @ Windows 10.

**Comment by jimhester** [comment] 2022-06-21 18:08
We could add something like this on the CI, to test in non-UTF-8 locales

https://github.com/r-lib/fs/blob/e10022f2df4571a8598a4caec4929d4b133566d9/.github/workflows/R-CMD-check.yaml#L37-L42

Hopefully that would reproduce the issue seen on that CRAN flavor.

**Comment by MichaelChirico** [comment] 2022-07-25 06:41
> Add link to blog post in pkgdown news menu

what does that entail, exactly 😅

**Comment by IndrajeetPatil** [comment] 2022-07-25 06:45
I think it means adding the following to the `_pkgdown.yml`:

```yaml
news:
  releases:
  - text: "Version 3.0.0"
    href: https://www.tidyverse.org/blog/2022/07/lintr-3-0-0/
```

**Comment by MichaelChirico** [comment] 2022-07-27 02:06
With #1470 the blog post link is finally on the site; closing this

**Closed by MichaelChirico** 2022-07-27 02:06 UTC
