### ISSUE TITLE
Automatic fixes

### ISSUE THREAD

**Issue by m-muecke** [r-lib/lintr#2609] opened 2024-06-14 20:07 UTC
Are there any plans of supporting automatic fixes for lints like other linters (ruff, biome, etc.) do?

**Comment by MichaelChirico** [comment] 2024-06-14 20:17
See #784

I'd say -- nice to have, but not on the radar right now.

TBH, it is in a gray area where it overlaps substantially with what {styler} is for, and {styler} is already built to handle this. I think getting {lintr} to also support this in all of the linters we offer is a very high labor intensity that I wouldn't prioritize myself in the near future.

Open to outside contributors making that effort if so motivated, OTOH.

**Comment by IndrajeetPatil** [comment] 2024-06-14 20:17
Duplicate of https://github.com/r-lib/lintr/issues/784

**Closed by MichaelChirico** 2024-06-14 20:17 UTC
