### ISSUE TITLE
Provide support for GitHub's Code Scanning API

### ISSUE THREAD

**Issue by jimhester** [r-lib/lintr#807] opened 2021-06-02 17:36 UTC
> GitHub recently released the Code Scanning API, which allows users to upload SAST scan results directly to GitHub. This allows developers to scan code on pull requests and use branch protection rules to disallow code contributions if they do not pass. 
>
> We've written a [detailed integration guide](https://partner.github.com/integration-resources/2021/03/09/pattern-integrating-with-code-scanning.html) that outlines how to upload a SARIF report to GitHub and run the project out of GitHub actions. If you'd be interested to add this to your project we can recommend LintR when we see projects written in R on GitHub automatically. Users would be able to use their free actions minutes and the code-scanning api on any open source project written in R.
>
> If you'd be interested to add Lintr to the collection of OSS scanners on GitHub I'd really appreciate it! Happy to send out a swag kit to you or whoever does the work, too. It'll definitely help people find the tool. 
> 
> If you don't have time or interest, no worries! We know being an OSS maintainer is sort of a thankless job sometimes and we appreciate you working on GitHub. I have your project in a backlog of projects that sometimes our team will pick up from. I'll try to see if we can make the code contribution directly, too.

**Comment by MichaelChirico** [comment] 2022-06-01 22:06
duplicate of #991

**Closed by MichaelChirico** 2022-06-01 22:06 UTC
Labels: feature
