### ISSUE TITLE
Add .lintr to .Rbuildignore when use_lintr() is run within a package

### ISSUE THREAD

**Issue by nr0cinu** [r-lib/lintr#2638] opened 2024-07-29 17:38 UTC
Hi,

this was once documented in the README, but was removed in https://github.com/r-lib/lintr/commit/910a55aca18666b99b070a751fed996590d8cede.

`usethis::use_build_ignore(".lintr")` could maybe be run automatically by `use_lintr()`?

Best,
Bela

**Comment by MichaelChirico** [comment] 2024-07-29 17:42
Duplicate of #1805

**Closed by MichaelChirico** 2024-07-29 17:42 UTC
Labels: duplicate
