### ISSUE TITLE
Adding SARIF result format support for lintr

### ISSUE THREAD

**Issue by shaopeng-gh** [r-lib/lintr#1341] opened 2022-06-01 21:37 UTC
Hello! We are interested in adding support for output in the open-standard SARIF format to the lintr. SARIF support is required to integrate it in [GitHub code scanning](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning). Doing so would make it available to every repo in GitHub and could result in increase in user base.

More about SARIF here:
[What is SARIF?](https://github.com/microsoft/sarif-tutorials/blob/main/docs/1-Introduction.md#what-is-sarif)
[Why SARIF?](https://github.com/microsoft/sarif-tutorials/blob/main/docs/1-Introduction.md#why-sarif)

If you agree, we will be happy to looking into necessary code changes in this repo and also creating a starter workflow in the GitHub starter workflow repo to make it available as a GitHub code scanner.

( Does the tool already has a flag logically like --format, if so we are looking at adding sarif to that list, if not let us know preferred way in R langue to provide arg what output format user want.
Feel free to let me know if have any guidance, thanks! )

I see previous related request #991 and #807 . Linking here.

Thanks,
Shaopeng

**Comment by MichaelChirico** [comment] 2022-06-01 22:07
thanks for the request! we are open to PRs.

closing this as duplicate of #991 to try and keep discussion in one place.

**Closed by MichaelChirico** 2022-06-01 22:07 UTC
