### ISSUE TITLE
Enhancement of `unreachable_code_linter` to Detect Unreachable Code in Loops

### ISSUE THREAD

**Issue by MEO265** [r-lib/lintr#2105] opened 2023-09-04 19:49 UTC
The `unreachable_code_linter` should also mark code inside if, else, for, and while loops as unreachable, especially when a return or stop function is called.

The following code currently generates only one annotation:

```r
x <- function() { 
  if(TRUE) { 
    stop('This is a test') 
    5+5 
  } 
  return(5L)
  4+4 
} 
```

And this one generates none:
```r
x <- function() { 
  if(TRUE) { 
    stop('This is a test') 
    5+5 
  } 
  4+4 
} 
```

**Comment by MichaelChirico** [comment] 2023-09-04 21:06
I think this is a duplicate of #1428, though I don't think if(TRUE) constitutes _unreachable_ code. I think it's more relevant for unnecessary _nesting_ (which we have a linter for, though not in {lintr}) yet IIRC

**Comment by MEO265** [comment] 2023-09-09 05:07
In loops, attention should also be paid to "next" and "break". 

@MichaelChirico I'm not sure if that's a part of what you might have meant in your TODO as well.
https://github.com/r-lib/lintr/blob/c8f00746501e041d2516da58ccca3e054cf305f1/tests/testthat/test-unreachable_code_linter.R#L175-L180

**Closed** 2023-10-09 01:49 UTC
Labels: feature
