### ISSUE TITLE
Upcoming placeholder `_`

### ISSUE THREAD

**Issue by renkun-ken** [r-lib/lintr#959] opened 2022-03-19 02:22 UTC
I'm playing with the upcoming placeholder `_` in R 4.2.0 (R Under development (unstable) (2022-03-17 r81925)), which allows the following expression:

```r
mtcars |> 
  lm(mpg ~ cyl, data = _)
```

The parse data seems straightforward:

```r
expr <- parse(text = "data |> fun(mpg ~ cyl, data = _)")
getParseData(expr)
```

```
   line1 col1 line2 col2 id parent                token terminal text
27     1    1     1   32 27      0                 expr    FALSE     
1      1    1     1    4  1      3               SYMBOL     TRUE data
3      1    1     1    4  3     27                 expr    FALSE     
2      1    6     1    7  2     27                 PIPE     TRUE   |>
25     1    9     1   32 25     27                 expr    FALSE     
4      1    9     1   11  4      6 SYMBOL_FUNCTION_CALL     TRUE  fun
6      1    9     1   11  6     25                 expr    FALSE     
5      1   12     1   12  5     25                  '('     TRUE    (
13     1   13     1   21 13     25                 expr    FALSE     
7      1   13     1   15  7      9               SYMBOL     TRUE  mpg
9      1   13     1   15  9     13                 expr    FALSE     
8      1   17     1   17  8     13                  '~'     TRUE    ~
10     1   19     1   21 10     12               SYMBOL     TRUE  cyl
12     1   19     1   21 12     13                 expr    FALSE     
11     1   22     1   22 11     25                  ','     TRUE    ,
17     1   24     1   27 17     25           SYMBOL_SUB     TRUE data
18     1   29     1   29 18     25               EQ_SUB     TRUE    =
19     1   31     1   31 19     20          PLACEHOLDER     TRUE    _
20     1   31     1   31 20     25                 expr    FALSE     
21     1   32     1   32 21     25                  ')'     TRUE    )
```

However, there are known limitations where `_` could only appear as a placeholder of a named argument and could only appear once, which makes all the following expression invalid:

```r
data |> 
  fun(mpg ~ cyl, data1 = _, data2 = _)
```

which produces the following parse error:

```
pipe placeholder may only appear once
```

```r
mtcars |> 
  lm(mpg ~ cyl, data = fun(_))
```

```
invalid use of pipe placeholder
```

Unfortunately, neither of the error messages contains the location information, so we don't know where is the error.

Should we suggest r-devel to include the location information in the error messages?

**Comment by AshesITR** [comment] 2022-03-19 08:44
That's a very good suggestion.

**Comment by MichaelChirico** [comment] 2022-03-21 00:47
I think the problem is it's non-trivial for the parser to know what line it's at when it reaches these errors.

It's fairly easy to get the parser to spit out _a_ line number for the errors, e.g.:

```
Index: src/main/gram.c
===================================================================
--- src/main/gram.c	(revision 81946)
+++ src/main/gram.c	(working copy)
@@ -3426,7 +3426,7 @@
 {
     for (SEXP rest = args; rest != R_NilValue; rest = CDR(rest))
 	if (CAR(rest) == R_PlaceholderToken)
-	    errorcall(rhs, _("pipe placeholder may only appear once"));
+	  errorcall(rhs, _("pipe placeholder may only appear once (line %d)"), ParseState.xxlineno);
 }
 
 static SEXP xxpipe(SEXP lhs, SEXP rhs)
@@ -3901,10 +3901,10 @@
 	case 4:                     /* Valid expr ';' terminated */
 	    if (checkForPlaceholder(R_PlaceholderToken, R_CurrentExpr))
 		errorcall(R_CurrentExpr,
-			  _("invalid use of pipe placeholder"));
+			  _("invalid use of pipe placeholder (line %d)"), ParseState.xxlineno);
 	    if (checkForPipeBind(R_CurrentExpr))
 		errorcall(R_CurrentExpr,
-			  _("invalid use of pipe bind symbol"));
+			  _("invalid use of pipe bind symbol (line %d)"), ParseState.xxlineno);
 	    *status = PARSE_OK;
 	    break;
 	}
```

but that line number will not be right. c.f.

```
mtcars |> 
  lm(mpg ~ cyl, data = fun(_))
# Error in lm(mtcars, mpg ~ cyl, data = fun("_")) : 
#   invalid use of pipe placeholder (line 3)
```

vs

```
mtcars |> 
  lm(mpg ~ cyl, data = fun(_)); print("hi")
# Error in lm(mtcars, mpg ~ cyl, data = fun("_")) : 
#   invalid use of pipe placeholder (line 2)
```

I don't understand the parser totally, but if you search gram.c for other uses of `ParseState.xxlineno`, they look more like errors that can fail immediately and so don't have this issue.

We can also see a slew of other parser errors in gram.c that don't give us line info.

It may be worth opening a bugzilla anyway so Luke can confirm whether this is possible.

**Comment by MichaelChirico** [comment] 2022-03-21 22:53
Almost forgot I already filed this 🙈 

https://bugs.r-project.org/show_bug.cgi?id=18259

I knew the issue sounded familiar...

**Comment by MichaelChirico** [comment] 2022-04-14 05:10
Closing for now.

**Closed by MichaelChirico** 2022-04-14 05:10 UTC

**Comment by dmurdoch** [comment] 2022-04-21 18:46
Just saw Luke's R-devel response referencing this.

There are some variables in bison/yacc that refer to each of the components of a pattern that was matched.  All of the errors have to do with the RHS of 

    lhs |> rhs

so the function handling that pattern needs to know the location of rhs, which is `&@3`, a pointer to a YYLTYPE structure.  Often the rhs will take up more than one line, but I don't think there's an easy way to pinpoint the location within that, so it's only easy to report the first line of the rhs, or the line range.  I have attached a patch that just does the first line; can you do some testing on it and see if you really want the whole range?  (The patch is big because I have a different version of bison than the one used in R, so src/main/gram.c gets lots of changes, but really the source is src/main/gram.y and the changes there are fairly small.  Here they are:

```
Index: src/main/gram.y
===================================================================
--- src/main/gram.y	(revision 82226)
+++ src/main/gram.y	(working copy)
@@ -360,7 +360,7 @@
 static SEXP	xxnxtbrk(SEXP);
 static SEXP	xxfuncall(SEXP, SEXP);
 static SEXP	xxdefun(SEXP, SEXP, SEXP, YYLTYPE *);
-static SEXP	xxpipe(SEXP, SEXP);
+static SEXP	xxpipe(SEXP, SEXP, YYLTYPE *);
 static SEXP	xxpipebind(SEXP, SEXP, SEXP);
 static SEXP	xxunary(SEXP, SEXP);
 static SEXP	xxbinary(SEXP, SEXP, SEXP);
@@ -469,7 +469,7 @@
 	|	expr OR expr			{ $$ = xxbinary($2,$1,$3);	setId(@$); }
 	|	expr AND2 expr			{ $$ = xxbinary($2,$1,$3);	setId(@$); }
 	|	expr OR2 expr			{ $$ = xxbinary($2,$1,$3);	setId(@$); }
-	|	expr PIPE expr			{ $$ = xxpipe($1,$3);  setId(@$); }
+	|	expr PIPE expr			{ $$ = xxpipe($1,$3,&@3);       setId(@$); }
 	|	expr PIPEBIND expr		{ $$ = xxpipebind($2,$1,$3);	setId(@$); }
 	|	expr LEFT_ASSIGN expr 		{ $$ = xxbinary($2,$1,$3);	setId(@$); }
 	|	expr RIGHT_ASSIGN expr 		{ $$ = xxbinary($2,$3,$1);	setId(@$); }
@@ -1181,29 +1181,29 @@
     return ans;
 }
 
-static void check_rhs(SEXP rhs)
+static void check_rhs(SEXP rhs, YYLTYPE *lloc)
 {
     /* rule out syntactically special functions */
     /* the IS_SPECIAL_SYMBOL bit is set in names.c */
     SEXP fun = CAR(rhs);
     if (TYPEOF(fun) == SYMSXP && IS_SPECIAL_SYMBOL(fun))
-	error("function '%s' not supported in RHS call of a pipe",
-	      CHAR(PRINTNAME(fun)));
+	error(_("function '%s' not supported in RHS call of a pipe (line %d)"),
+	      CHAR(PRINTNAME(fun)), lloc->first_line);
 }
 
-static void checkTooManyPlaceholders(SEXP rhs, SEXP args)
+static void checkTooManyPlaceholders(SEXP rhs, SEXP args, YYLTYPE *lloc)
 {
     for (SEXP rest = args; rest != R_NilValue; rest = CDR(rest))
 	if (CAR(rest) == R_PlaceholderToken)
-	    errorcall(rhs, _("pipe placeholder may only appear once"));
+	    errorcall(rhs, _("pipe placeholder may only appear once (line %d)"), lloc->first_line);
 }
 
-static SEXP xxpipe(SEXP lhs, SEXP rhs)
+static SEXP xxpipe(SEXP lhs, SEXP rhs, YYLTYPE *lloc_rhs)
 {
     SEXP ans;
     if (GenerateCode) {
 	if (TYPEOF(rhs) != LANGSXP)
-	    error(_("The pipe operator requires a function call as RHS"));
+	    error(_("The pipe operator requires a function call as RHS (line %d)"), lloc_rhs->first_line);
 
 	/* allow x => log(x) on RHS */
 	if (CAR(rhs) == R_PipeBindSymbol) {
@@ -1210,7 +1210,7 @@
 	    SEXP var = CADR(rhs);
 	    SEXP expr = CADDR(rhs);
 	    if (TYPEOF(var) != SYMSXP)
-		error(_("RHS variable must be a symbol"));
+		error(_("RHS variable must be a symbol (line %d)"), lloc_rhs->first_line);
 	    SEXP alist = list1(R_MissingArg);
 	    SET_TAG(alist, var);
 	    SEXP fun = lang4(R_FunctionSymbol, alist, expr, R_NilValue);
@@ -1217,9 +1217,9 @@
 	    return lang2(fun, lhs);
 	}
 
-	/* check for placehilder in the RHS function */
+	/* check for placeholder in the RHS function */
 	if (checkForPlaceholder(R_PlaceholderToken, CAR(rhs)))
-	    error(_("pipe placeholder cannot be used in the RHS function"));
+	    error(_("pipe placeholder cannot be used in the RHS function (line %d)"), lloc_rhs->first_line);
 
 	/* allow top-level placeholder */
 	for (SEXP a = CDR(rhs); a != R_NilValue; a = CDR(a))
@@ -1226,13 +1226,13 @@
 	    if (CAR(a) == R_PlaceholderToken) {
 		if (TAG(a) == R_NilValue)
 		    error(_("pipe placeholder can only be used as a "
-			    "named argument"));
-		checkTooManyPlaceholders(rhs, CDR(a));
+			    "named argument (line %d)"), lloc_rhs->first_line);
+		checkTooManyPlaceholders(rhs, CDR(a), lloc_rhs);
 		SETCAR(a, lhs);
 		return rhs;
 	    }
 	
-	check_rhs(rhs);
+	check_rhs(rhs, lloc_rhs);
 	
         SEXP fun = CAR(rhs);
         SEXP args = CDR(rhs);
```

**Comment by dmurdoch** [comment] 2022-04-21 19:02
Okay, here's the diff of src/main/gram.y.  To get gram.c, apply this in the source tree, then run (still in the source tree!) `make gram.c`.

```
Index: src/main/gram.y
===================================================================
--- src/main/gram.y	(revision 82226)
+++ src/main/gram.y	(working copy)
@@ -360,7 +360,7 @@
 static SEXP	xxnxtbrk(SEXP);
 static SEXP	xxfuncall(SEXP, SEXP);
 static SEXP	xxdefun(SEXP, SEXP, SEXP, YYLTYPE *);
-static SEXP	xxpipe(SEXP, SEXP);
+static SEXP	xxpipe(SEXP, SEXP, YYLTYPE *);
 static SEXP	xxpipebind(SEXP, SEXP, SEXP);
 static SEXP	xxunary(SEXP, SEXP);
 static SEXP	xxbinary(SEXP, SEXP, SEXP);
@@ -469,7 +469,7 @@
 	|	expr OR expr			{ $$ = xxbinary($2,$1,$3);	setId(@$); }
 	|	expr AND2 expr			{ $$ = xxbinary($2,$1,$3);	setId(@$); }
 	|	expr OR2 expr			{ $$ = xxbinary($2,$1,$3);	setId(@$); }
-	|	expr PIPE expr			{ $$ = xxpipe($1,$3);  setId(@$); }
+	|	expr PIPE expr			{ $$ = xxpipe($1,$3,&@3);       setId(@$); }
 	|	expr PIPEBIND expr		{ $$ = xxpipebind($2,$1,$3);	setId(@$); }
 	|	expr LEFT_ASSIGN expr 		{ $$ = xxbinary($2,$1,$3);	setId(@$); }
 	|	expr RIGHT_ASSIGN expr 		{ $$ = xxbinary($2,$3,$1);	setId(@$); }
@@ -1181,29 +1181,29 @@
     return ans;
 }
 
-static void check_rhs(SEXP rhs)
+static void check_rhs(SEXP rhs, YYLTYPE *lloc)
 {
     /* rule out syntactically special functions */
     /* the IS_SPECIAL_SYMBOL bit is set in names.c */
     SEXP fun = CAR(rhs);
     if (TYPEOF(fun) == SYMSXP && IS_SPECIAL_SYMBOL(fun))
-	error("function '%s' not supported in RHS call of a pipe",
-	      CHAR(PRINTNAME(fun)));
+	error(_("function '%s' not supported in RHS call of a pipe (line %d)"),
+	      CHAR(PRINTNAME(fun)), lloc->first_line);
 }
 
-static void checkTooManyPlaceholders(SEXP rhs, SEXP args)
+static void checkTooManyPlaceholders(SEXP rhs, SEXP args, YYLTYPE *lloc)
 {
     for (SEXP rest = args; rest != R_NilValue; rest = CDR(rest))
 	if (CAR(rest) == R_PlaceholderToken)
-	    errorcall(rhs, _("pipe placeholder may only appear once"));
+	    errorcall(rhs, _("pipe placeholder may only appear once (line %d)"), lloc->first_line);
 }
 
-static SEXP xxpipe(SEXP lhs, SEXP rhs)
+static SEXP xxpipe(SEXP lhs, SEXP rhs, YYLTYPE *lloc_rhs)
 {
     SEXP ans;
     if (GenerateCode) {
 	if (TYPEOF(rhs) != LANGSXP)
-	    error(_("The pipe operator requires a function call as RHS"));
+	    error(_("The pipe operator requires a function call as RHS (line %d)"), lloc_rhs->first_line);
 
 	/* allow x => log(x) on RHS */
 	if (CAR(rhs) == R_PipeBindSymbol) {
@@ -1210,7 +1210,7 @@
 	    SEXP var = CADR(rhs);
 	    SEXP expr = CADDR(rhs);
 	    if (TYPEOF(var) != SYMSXP)
-		error(_("RHS variable must be a symbol"));
+		error(_("RHS variable must be a symbol (line %d)"), lloc_rhs->first_line);
 	    SEXP alist = list1(R_MissingArg);
 	    SET_TAG(alist, var);
 	    SEXP fun = lang4(R_FunctionSymbol, alist, expr, R_NilValue);
@@ -1217,9 +1217,9 @@
 	    return lang2(fun, lhs);
 	}
 
-	/* check for placehilder in the RHS function */
+	/* check for placeholder in the RHS function */
 	if (checkForPlaceholder(R_PlaceholderToken, CAR(rhs)))
-	    error(_("pipe placeholder cannot be used in the RHS function"));
+	    error(_("pipe placeholder cannot be used in the RHS function (line %d)"), lloc_rhs->first_line);
 
 	/* allow top-level placeholder */
 	for (SEXP a = CDR(rhs); a != R_NilValue; a = CDR(a))
@@ -1226,13 +1226,13 @@
 	    if (CAR(a) == R_PlaceholderToken) {
 		if (TAG(a) == R_NilValue)
 		    error(_("pipe placeholder can only be used as a "
-			    "named argument"));
-		checkTooManyPlaceholders(rhs, CDR(a));
+			    "named argument (line %d)"), lloc_rhs->first_line);
+		checkTooManyPlaceholders(rhs, CDR(a), lloc_rhs);
 		SETCAR(a, lhs);
 		return rhs;
 	    }
 	
-	check_rhs(rhs);
+	check_rhs(rhs, lloc_rhs);
 	
         SEXP fun = CAR(rhs);
         SEXP args = CDR(rhs);
@@ -1670,7 +1670,7 @@
 	case 4:                     /* Valid expr ';' terminated */
 	    if (checkForPlaceholder(R_PlaceholderToken, R_CurrentExpr))
 		errorcall(R_CurrentExpr,
-			  _("invalid use of pipe placeholder"));
+			  _("invalid use of pipe placeholder (before line %d)"), yylloc.first_line);
 	    if (checkForPipeBind(R_CurrentExpr))
 		errorcall(R_CurrentExpr,
 			  _("invalid use of pipe bind symbol"));
```

**Comment by dmurdoch** [comment] 2022-04-26 20:41
I ended up putting this on the bug page as https://bugs.r-project.org/show_bug.cgi?id=18328 .  
My comment on the bug page describes the current state.

The original patch was close to what I posted here (and have since deleted), but the latest variation is more ambitious:  it converts most parser errors into condition objects, all of which have information about the filename, line and column of the error.  (Sometimes the information is imprecise, just because it's hard to pick the right spot.)  It's still subject to change before R Core would consider incorporating it so don't take it too seriously, but comments about what works and what doesn't could influence things.

**Comment by MichaelChirico** [comment] 2022-06-04 09:18
Looks like this is merged now!

![Screenshot_20220604-021457](https://user-images.githubusercontent.com/7606389/171992972-a68551a9-6590-4605-b726-4a11e9dd4f86.jpg)

thanks @dmurdoch!

**Comment by dmurdoch** [comment] 2022-06-04 09:26
I think they'd still like to hear comments from the lintr team about possible changes.  This is only in R-devel, and it won't be released for 10 months, so there's lots of time to try it out.

**Comment by beyondpie** [comment] 2023-09-16 23:24
Hi there,
I still have errors on `y |> x => f(x) ` errors on "=>" 
 [lintr] '=>' is disabled; set '_R_USE_PIPEBIND_' envvar to a true value to enable it. (57:6)

- I've set Sys.setenv("_R_USE_PIPEBIND_" = TRUE) in this script. And codes can be run. Do you know how can I remove this error warning?

**Comment by AshesITR** [comment] 2023-09-17 07:20
@beyondpie The envvar needs to be set when you run `lint()`. Please file a new issue if you run into problems with the feature.
