### ISSUE TITLE
object_name_linter warning with R6 class

### ISSUE THREAD

**Issue by pkrog** [r-lib/lintr#2547] opened 2024-04-02 14:59 UTC
Warning message:
```
R/Request.R|24 col 1 s| [object_name_linter] Variable and function name style should match snake_case or symbols.                                                                              
|| Request <- R6::R6Class("Request",
|| ^~~~~~~
```

However R6 classes, as many other languages and class systems, have UpperCamelCase names. See <https://adv-r.hadley.nz/r6.html#r6-classes>.

**Comment by MichaelChirico** [comment] 2024-04-02 15:16
For now your best bet is to add `CamelCase` as a valid style in your config:

```r
object_name_linter(c("snake_case", "CamelCase", "symbols"))
```

Beyond that would be a duplicate of #1104

**Closed by MichaelChirico** 2024-04-02 15:16 UTC
