### ISSUE TITLE
pkgdown shows lintr version 3.0.2 instead of 3.1.0

### ISSUE THREAD

**Issue by nicholas-masel** [r-lib/lintr#2045] opened 2023-08-04 12:25 UTC
![image](https://github.com/r-lib/lintr/assets/61123199/f895eec8-d8ac-414a-8bff-edff7c4f80a8)

**Comment by MichaelChirico** [comment] 2023-08-05 19:12
Hmm I don't see anything wrong with our `_pkgdown.yml` setup. In particular, we're using `development_mode: auto` which should result in the homepage reflecting what's on CRAN:

https://github.com/r-lib/pkgdown/blob/c9206802f2888992de92aa41f517ba7812f05331/vignettes/how-to-update-released-site.Rmd#L77-L102

I also looked at a few CRAN mirrors and they all show 3.1.0.

Might be a pkgdown bug.

**Comment by MichaelChirico** [comment] 2023-08-05 19:20
Looking at the {pkgdown} logs, I see mention of the RStudio Package Manager, which points me to this PACKAGES metadata page:

https://packagemanager.posit.co/cran/__linux__/jammy/latest/src/contrib/PACKAGES

I see {lintr} listed as 3.1.0 there too.

**Comment by MichaelChirico** [comment] 2023-08-05 19:24
I'll assume this will resolve itself soon. I'll check again after the next commit to `main`.

One thing I _do_ see is not all the 3.1.0 checks have completed on CRAN yet:

https://cran.r-project.org/web/checks/check_results_lintr.html

So I'll also wait for 1 month after the CRAN release date (i.e. August 19) before officially calling this a bug.

**Comment by IndrajeetPatil** [comment] 2023-08-09 07:22
My guess is that this happened because, even before the website was built when package version was `3.1.0`, a new commit was pushed to the default branch that bumped the package to devel version (`3.1.0.9000`). Indeed, [the devel version](https://lintr.r-lib.org/dev/) of the website is as expected.

**Comment by AshesITR** [comment] 2023-08-09 18:36
Is there a way to manually trigger a build for 3.1.0 ex post?

The R build checks seem to all have completed by now.

**Comment by MichaelChirico** [comment] 2023-08-11 02:47
cc @hadley as {pkgdown} maintainer -- is this pkgdown WAI here?

**Comment by IndrajeetPatil** [comment] 2023-08-11 03:20
As suspected, pkgdown workflow (or any other workflow for that matter) wasn't run for some reason for the commit in which the version was bumped to `3.1.0`:

<img width="1262" alt="Screenshot 2023-08-11 at 08 47 57" src="https://github.com/r-lib/lintr/assets/11330453/0ec76e0c-5ad0-48f3-8b4c-f952986f1713">

**Comment by hadley** [comment] 2023-08-11 14:16
This should be fixed momentarily — I triggered a manual pkgdown run from the v3.1.0 tag.

**Comment by AshesITR** [comment] 2023-08-11 14:26
As for the root cause my suspicion is that the two commits were pushed in one go, causing GHA to skip the first commit.

@jimhester not sure if you know what you did a month ago, but I'd try pushing the next release commit separately from the `use_dev_version()` commit.

**Closed** 2023-08-11 14:27 UTC
Labels: documentation

**Comment by jimhester** [comment] 2023-08-11 18:30
@AshesITR your guess is probably correct, I would guess I pushed both commits at the same time. This isn't the first time a similar issue has happened on a repo, so likely my workflow should probably be adjusted to avoid this problem...

**Comment by MichaelChirico** [comment] 2023-08-11 19:51
Filed https://github.com/r-lib/pkgdown/issues/2331 as it seems like this is a pretty easy mistake to make.
