### ISSUE TITLE
lint code in examples

### ISSUE THREAD

**Issue by jimhester** [r-lib/lintr#61] opened 2015-03-06 19:21 UTC
It would be nice to lint code in both regular examples as well as roxygen comments.

I guess there is potential errors in someone having `#'` in a comment but not using roxygen.  However that seems like a rare situation.

**Comment by MichaelChirico** [comment] 2022-04-05 04:08
Marking as a duplicate of #265. I'm not sure how much motivation there is to lint non-roxygen2 examples/code, so that issue should cover the main use case.

**Closed by MichaelChirico** 2022-04-05 04:08 UTC
Labels: duplicate, feature
